"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Scope = "local" | "broad";
type Lead = { id: string; firm: string; city: string; state: string; scope: Scope; adCount: number; activeSince: string; daysLive: number; platforms: string[]; adTheme: string; adCopy: string; landingUrl?: string; websiteUrl?: string; pageUrl?: string; libraryUrl: string; confidence: "high" | "medium" };
type Generated = { subject: string; body: string; brief: string };
type Contact = { firstName?: string; email?: string; source?: string; note?: string };
type SavedScan = { id: string; label: string; savedAt: string; state: string; city: string; keyword: string; scope: Scope; leads: Lead[]; notice: string };

const savedKey = "lawyer-ad-signal.saved-scans.v1";
const states: Record<string, string> = { AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California", CO: "Colorado", CT: "Connecticut", DE: "Delaware", FL: "Florida", GA: "Georgia", HI: "Hawaii", ID: "Idaho", IL: "Illinois", IN: "Indiana", IA: "Iowa", KS: "Kansas", KY: "Kentucky", LA: "Louisiana", ME: "Maine", MD: "Maryland", MA: "Massachusetts", MI: "Michigan", MN: "Minnesota", MS: "Mississippi", MO: "Missouri", MT: "Montana", NE: "Nebraska", NV: "Nevada", NH: "New Hampshire", NJ: "New Jersey", NM: "New Mexico", NY: "New York", NC: "North Carolina", ND: "North Dakota", OH: "Ohio", OK: "Oklahoma", OR: "Oregon", PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina", SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont", VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming", DC: "District of Columbia" };
const citySuggestions: Record<string, string[]> = { VA: ["Fairfax", "Arlington", "Alexandria", "Richmond", "Virginia Beach", "Norfolk", "Roanoke", "Chesapeake", "Ashburn", "Tysons"], MD: ["Bethesda", "Baltimore", "Rockville", "Silver Spring", "Annapolis", "Frederick", "Gaithersburg"], DC: ["Washington"], FL: ["Miami", "Tampa", "Orlando", "Jacksonville", "Fort Lauderdale", "Naples", "St. Petersburg"], TX: ["Austin", "Dallas", "Houston", "San Antonio", "Fort Worth", "Plano", "Arlington"], CA: ["Los Angeles", "San Diego", "San Francisco", "Sacramento", "San Jose", "Oakland", "Irvine"], NY: ["New York", "Buffalo", "Albany", "Rochester", "Syracuse", "Yonkers"] };
const practiceSuggestions = ["lawyer", "attorney", "personal injury", "car accident", "truck accident", "wrongful death", "medical malpractice", "workers compensation", "criminal defense", "DUI", "family law", "divorce", "child custody", "estate planning", "probate", "immigration", "bankruptcy", "real estate law", "employment law"];

function daysLabel(days: number) { if (days >= 365) return "1 year+"; if (days >= 180) return "6 months+"; if (days >= 90) return "90 days+"; if (days >= 30) return "30 days+"; return `${Math.max(days, 1)} days`; }
function domainLabel(value?: string) { try { return new URL(value || "").hostname.replace(/^www\./, ""); } catch { return ""; } }
function readSavedScans(): SavedScan[] { if (typeof window === "undefined") return []; try { return JSON.parse(window.localStorage.getItem(savedKey) || "[]"); } catch { return []; } }

export default function Home() {
  const [state, setState] = useState("VA"); const [city, setCity] = useState("Fairfax"); const [keyword, setKeyword] = useState("personal injury"); const [scope, setScope] = useState<Scope>("local");
  const [leads, setLeads] = useState<Lead[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [mode, setMode] = useState<"live" | "sample" | null>(null); const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(false); const [elapsed, setElapsed] = useState(0); const [savedScans, setSavedScans] = useState<SavedScan[]>(readSavedScans);
  const [firstName, setFirstName] = useState(""); const [contact, setContact] = useState<Contact | null>(null); const [findingContact, setFindingContact] = useState(false); const [findingWebsite, setFindingWebsite] = useState(false);
  const [generated, setGenerated] = useState<Generated | null>(null); const [generating, setGenerating] = useState(false); const [importText, setImportText] = useState("");
  const selected = useMemo(() => leads.find((lead) => lead.id === selectedId) ?? null, [leads, selectedId]);

  useEffect(() => { if (!loading) return; const started = Date.now(); const timer = window.setInterval(() => setElapsed(Math.floor((Date.now() - started) / 1000)), 1000); return () => window.clearInterval(timer); }, [loading]);
  function persist(next: SavedScan[]) { setSavedScans(next); window.localStorage.setItem(savedKey, JSON.stringify(next)); }
  function saveScan(nextLeads: Lead[], nextNotice: string) { const item: SavedScan = { id: `${Date.now()}-${city}`, label: `${city || "U.S."} · ${keyword || "lawyer"}`, savedAt: new Date().toLocaleDateString(), state, city, keyword, scope, leads: nextLeads, notice: nextNotice }; persist([item, ...savedScans.filter((scan) => scan.label !== item.label)].slice(0, 20)); }
  function restoreScan(scan: SavedScan) { setState(scan.state); setCity(scan.city); setKeyword(scan.keyword); setScope(scan.scope); setLeads(scan.leads); setNotice(`${scan.notice} Restored from this browser.`); setMode("live"); setSelectedId(scan.leads[0]?.id ?? null); setGenerated(null); setContact(null); }
  function updateLead(id: string, changes: Partial<Lead>) { setLeads((items) => items.map((item) => item.id === id ? { ...item, ...changes } : item)); }

  async function runScan(event: FormEvent) {
    event.preventDefault(); setLoading(true); setElapsed(0); setNotice(""); setGenerated(null); setContact(null);
    try {
      const payload = { state, city, keyword, scope };
      let response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      let data = await response.json();
      if (!response.ok && response.status !== 202) throw new Error(data.error || "The scan could not be completed.");
      while (data.status === "running") {
        setNotice(data.notice || "Scanning active ads...");
        await new Promise((resolve) => window.setTimeout(resolve, 3500));
        response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, runId: data.runId }) });
        data = await response.json();
        if (!response.ok && response.status !== 202) throw new Error(data.error || "The scan could not be completed.");
      }
      setLeads(data.leads); setMode(data.mode); setNotice(data.notice || ""); setSelectedId(data.leads[0]?.id ?? null); saveScan(data.leads, data.notice || "");
    }
    catch (error) { setNotice(error instanceof Error ? error.message : "The scan could not be completed."); }
    finally { setLoading(false); }
  }

  function importAds() { try { const parsed = JSON.parse(importText); const items = Array.isArray(parsed) ? parsed : parsed.leads; if (!Array.isArray(items)) throw new Error("Paste a JSON array of ad records."); const normalized: Lead[] = items.slice(0, 50).map((item: Record<string, unknown>, index: number) => ({ id: String(item.id || item.adArchiveId || item.ad_id || `import-${index}`), firm: String(item.firm || item.pageName || item.page_name || item.advertiser || "Unknown firm"), city, state, scope, adCount: Number(item.adCount || item.collationCount || 1), activeSince: String(item.activeSince || item.startDateFormatted || item.startDate || item.start_date || "Unknown"), daysLive: Number(item.daysLive || item.duration_days || item.runningDays || 1), platforms: Array.isArray(item.platforms) ? item.platforms.map(String) : ["Meta"], adTheme: String(item.adTheme || item.title || item.headline || keyword || "legal services"), adCopy: String(item.adCopy || item.ad_text || item.body || item.text || item.caption || "Active legal-services ad"), landingUrl: item.landingUrl ? String(item.landingUrl) : item.link_url ? String(item.link_url) : undefined, websiteUrl: item.websiteUrl ? String(item.websiteUrl) : undefined, pageUrl: item.pageUrl ? String(item.pageUrl) : item.page_url ? String(item.page_url) : undefined, libraryUrl: String(item.libraryUrl || item.ad_snapshot_url || item.inputUrl || "https://www.facebook.com/ads/library/"), confidence: "medium" })); setLeads(normalized); setMode("live"); setSelectedId(normalized[0]?.id ?? null); setNotice(`${normalized.length} imported ad records are ready.`); } catch (error) { setNotice(error instanceof Error ? error.message : "The import could not be read."); } }

  async function findWebsite() { if (!selected) return; setFindingWebsite(true); try { const response = await fetch("/api/website", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lead: selected }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No official website was found."); updateLead(selected.id, { websiteUrl: data.websiteUrl }); setNotice(data.source || "Website ready."); } catch (error) { setNotice(error instanceof Error ? error.message : "No official website was found."); } finally { setFindingWebsite(false); } }
  async function findContact() { if (!selected) return; setFindingContact(true); setContact(null); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lead: selected }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No public contact was found."); setContact(data); if (data.firstName) setFirstName(data.firstName); } catch (error) { setNotice(error instanceof Error ? error.message : "No public contact was found."); } finally { setFindingContact(false); } }
  async function generateEmail() { if (!selected || !firstName.trim()) return; setGenerating(true); setGenerated(null); try { const response = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lead: selected, firstName: firstName.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "The email could not be generated."); setGenerated(data); } catch (error) { setNotice(error instanceof Error ? error.message : "The email could not be generated."); } finally { setGenerating(false); } }
  const website = selected?.websiteUrl || selected?.landingUrl; const gmailHref = generated && contact?.email ? `https://mail.google.com/mail/u/0/?view=cm&fs=1&to=${encodeURIComponent(contact.email)}&su=${encodeURIComponent(generated.subject)}&body=${encodeURIComponent(generated.body)}` : "";

  return <main>
    <header className="topbar"><div className="brand"><span className="brandMark">LS</span><span>Lawyer Ad Signal</span></div><div className="privacy">Private workspace</div></header>
    <section className="hero shell"><div className="eyebrow"><span /> Find firms already buying attention</div><h1>Turn active lawyer ads<br />into better cold emails.</h1><p className="lede">Use strict local evidence when geography matters, or switch to a clear U.S.-wide research list.</p>
      <form className="searchPanel searchPanelWide" onSubmit={runScan}>
        <label><span>Search type</span><select value={scope} onChange={(event) => setScope(event.target.value as Scope)}><option value="local">Local evidence only</option><option value="broad">U.S. broad</option></select></label>
        <label><span>State</span><select value={state} onChange={(event) => setState(event.target.value)}>{Object.entries(states).map(([code, name]) => <option key={code} value={code}>{name}</option>)}</select></label>
        <label><span>City</span><input list="city-options" value={city} onChange={(event) => setCity(event.target.value)} placeholder="Fairfax" disabled={scope === "broad"} /></label>
        <label className="keywordField"><span>Practice area or keyword</span><input list="practice-options" value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="lawyer" /></label>
        <button className="scanButton" disabled={loading}>{loading ? `Scanning · ${Math.floor(elapsed / 60)}:${String(elapsed % 60).padStart(2, "0")}` : "Scan active ads"}<b>→</b></button>
      </form>
      <datalist id="city-options">{(citySuggestions[state] || []).map((name) => <option key={name} value={name} />)}</datalist><datalist id="practice-options">{practiceSuggestions.map((name) => <option key={name} value={name} />)}</datalist>
      {loading && <div className="scanProgress" role="status" aria-live="polite"><span />Searching active ads. This can take up to two minutes.</div>}
      <div className="truthNote"><b>Local evidence only:</b> shows advertisers with the selected city or state visible in the ad/page data. It will exclude uncertain matches rather than relabeling unrelated firms as local. <b>Spend control:</b> scans run only when you press Scan.</div>
      {savedScans.length > 0 && <div className="savedScans"><b>Saved in this browser</b><div>{savedScans.slice(0, 6).map((scan) => <button key={scan.id} onClick={() => restoreScan(scan)}>{scan.label}<small>{scan.savedAt}</small></button>)}</div></div>}
    </section>
    {(notice || leads.length > 0) && <section className="workspace shell"><div className="workspaceHead"><div><p className="sectionKicker">Signal board</p><h2>{leads.length ? `${leads.length} firms to review` : "No results yet"}</h2></div>{mode && <span className={`mode ${mode}`}>{mode === "live" ? "Live data" : "Sample mode"}</span>}</div>{notice && <div className="notice">{notice}</div>}
      <div className="board"><div className="leadList">{leads.map((lead) => <button key={lead.id} className={`leadCard ${selectedId === lead.id ? "selected" : ""}`} onClick={() => { setSelectedId(lead.id); setGenerated(null); setContact(null); setFirstName(""); }}><div className="leadTop"><span className="firm">{lead.firm}</span><span className={`confidence ${lead.confidence}`}>{lead.scope === "local" ? "local evidence" : "broad"}</span></div><div className="metaLine"><span>{lead.scope === "local" ? `${lead.city}, ${lead.state}` : "U.S. broad search"}</span><span>{lead.adCount} active creative{lead.adCount === 1 ? "" : "s"}</span></div><p>{lead.adTheme}</p><div className="signalLine"><span className="pulse" /> Running {daysLabel(lead.daysLive)}</div></button>)}</div>
        <aside className="detailPanel">{selected ? <><div className="detailTitle"><div><span>Selected signal</span><h3>{selected.firm}</h3></div><a href={selected.libraryUrl} target="_blank" rel="noreferrer">Verify ad →</a></div><div className="stats"><div><b>{selected.adCount}</b><span>active creatives</span></div><div><b>{daysLabel(selected.daysLive)}</b><span>oldest active ad</span></div><div><b>{selected.platforms.join(" + ")}</b><span>placements seen</span></div></div><div className="evidence"><span>Ad evidence</span><p>{selected.adCopy}</p></div>
          <div className="websiteBox"><span>Firm website</span>{website ? <a href={website} target="_blank" rel="noreferrer">{domainLabel(website)} ↗</a> : <em>Not found yet</em>}<div>{selected.pageUrl && <a href={selected.pageUrl} target="_blank" rel="noreferrer">Open Facebook page</a>}<button className="contactButton" onClick={findWebsite} disabled={findingWebsite}>{findingWebsite ? "Finding website..." : website ? "Refresh website" : "Find official website"}</button></div></div>
          <div className="contactActions"><button className="contactButton" onClick={findContact} disabled={findingContact || !website}>{findingContact ? "Checking website..." : "Find public contact"}</button>{!website && <span>Find the website first.</span>}</div>{contact && <div className="contactResult"><b>{contact.email || "No email found"}</b>{contact.firstName && <span> · first name: {contact.firstName}</span>}<small>{contact.source || contact.note}</small></div>}
          <label className="nameField"><span>Contact first name</span><input value={firstName} onChange={(event) => setFirstName(event.target.value)} placeholder="John" /></label><p className="truthNote"><b>Email offer:</b> the first email leads with the active-ad topic and three YouTube angles—not thumbnail production. Confirm the contact before sending.</p><button className="generateButton" onClick={generateEmail} disabled={!firstName.trim() || generating}>{generating ? "Writing..." : "Generate email for this account"}</button>
          {generated && <div className="generated"><div className="generatedHead"><span>Ready to review</span><div className="emailActions">{gmailHref && <a href={gmailHref} target="_blank" rel="noreferrer">Review in Gmail</a>}<button onClick={() => navigator.clipboard.writeText(`Subject: ${generated.subject}\n\n${generated.body}`)}>Copy email</button></div></div><p className="subject"><b>Subject:</b> {generated.subject}</p><p className="emailBody">{generated.body}</p><details><summary>View the one-page brief</summary><pre>{generated.brief}</pre></details></div>}
        </> : <div className="empty">Run a scan, then choose a firm.</div>}</aside></div>
      <details className="importer"><summary>Import ad JSON instead</summary><p>Use this if you already exported records from Apify or another provider.</p><textarea value={importText} onChange={(event) => setImportText(event.target.value)} placeholder='[{"pageName":"Example Law","adCopy":"Injured in a crash?"}]' /><button onClick={importAds}>Import records</button></details>
    </section>}<footer className="shell"><span>Lawyer Ad Signal</span><p>Active-ad research + truthful opportunity emails.</p></footer>
  </main>;
}
